CREATE TABLE IF NOT EXISTS anime (
    mal_id INTEGER PRIMARY KEY,
    title TEXT NOT NULL,
    title_english TEXT,
    title_japanese TEXT,
    type_ TEXT,
    source_ TEXT,
    episodes INTEGER,
    status_ TEXT,
    airing BOOLEAN,
    aired_from DATE,
    aired_to DATE,
    duration TEXT,
    rating TEXT,
    score NUMERIC(4,2),
    scored_by INTEGER,
    rank_ INTEGER,
    popularity INTEGER,
    members INTEGER,
    favorites INTEGER,
    synopsis TEXT,
    year_ INTEGER,
    season TEXT,
    studios TEXT,
    genres TEXT,
    themes TEXT,
    demographics TEXT
);
